sudo: false
language: go
env:
  - GO111MODULE=on
go:
  - 1.16.x
git:
  depth: 1
before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
script:
  - golangci-lint run
  - go test -v -race ./...
